[build-system]
requires = ["setuptools>=61", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "data_copilot"
description = "The data_copilot web application"
readme = "README.rst"
requires-python = ">=3.10"
keywords = ["data_copilot"]
authors = [
  {name = "Modulos AG", email = "contact@modulos.ai" }
]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Intended Audience :: Developers",
  "Natural Language :: English",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
]
dynamic = ["version"]
# dependencies = [
#     "fastapi==0.89.1",
#     "uvicorn==0.20.0",
#     "sqlalchemy==2.0.4",
#     "psycopg2-binary==2.9.5",
#     "email-validator==1.3.0",
#     "python-jose==3.3.0",
#     "passlib==1.7.4",
#     "python-multipart==0.0.5",
#     "bcrypt==4.0.1",
#     "azure-storage-blob==12.14.1",
#     "aiohttp==3.8.3",
#     "azure-identity==1.12.0",
#     "python-dotenv==0.21.1",
#     "azure-storage-file-datalake==12.9.1",
#     "fastapi-sso==0.6.4"
# ]
# # List additional groups of dependencies here (e.g. development
# # dependencies). Users will be able to install these using the "extras"
# # syntax, for example:
# #
# #   $ pip install .[dev]
# [project.optional-dependencies]
# dev = [
#     'black == 22.12.0',
#     'tox == 4.3.5',
# ]

[project.urls]
"Homepage" = "https://github.com/Modulos/data_copilot/"
"Bug Reports" = "https://github.com/Modulos/data_copilot/issues"
"Source" = "https://github.com/Modulos/data_copilot/"


[tool.setuptools.packages.find]
include = ["data_copilot"]

[tool.setuptools_scm]
write_to = "_version.py"

[tool.pytest.ini_options]
minversion = "3.0"
testpaths = ["tests"]
addopts = [
    "--import-mode=importlib",
]
