name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-test:
    strategy:
      matrix:
        python: ["3.10"]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install test dependencies
        run: python -m pip install -U tox
      - name: Tox run
        run: tox
        env:
          FURY_AUTH: ${{ secrets.FURY_AUTH }}

  frontend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: data_copilot/frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install modules
        run: npm install
      - name: ESlint run
        run: npm run lint
