name: Create a new release

on:
  workflow_dispatch:
    inputs:
      increment:
        type: choice
        description: Version increment (major.minor.patch)
        options: 
        - major
        - minor
        - patch

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Create new release
        run: python .github/scripts/release.py ${{ github.event.inputs.increment }}
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}